adjust scripts for help2man
Signed-off-by: Maciej Barć <xgqt@protonmail.com>

diff --git a/scripts/.local/share/bin/extractor b/scripts/.local/share/bin/extractor
--- a/scripts/.local/share/bin/extractor
+++ b/scripts/.local/share/bin/extractor
@@ -26,8 +26,55 @@ trap 'exit 128' INT
 export PATH
 
 
-if [ -f "${1}" ]; then
-    case ${1} in
+prog_name="$(basename "${0}")"
+prog_desc="extract a archive file"
+prog_args="FILE"
+
+
+usage() {
+    cat <<EOF
+Usage: ${prog_name} [OPTION]... ${prog_args}
+${prog_name} - ${prog_desc}
+
+Options:
+    -V, --version  show program version
+    -h, --help     show avalible options
+EOF
+}
+
+version() {
+    cat <<EOF
+${prog_name} 9999
+
+Copyright (c) 2020-2021, Maciej Barć <xgqt@protonmail.com>
+Licensed under the GNU GPL v3 License
+EOF
+}
+
+
+case "${1}"
+in
+    -h | -help | --help )
+        usage
+        exit 0
+        ;;
+    -V | -version | --version )
+        version
+        exit 0
+        ;;
+    -* )
+        version
+        echo
+        usage
+        exit 1
+        ;;
+esac
+
+
+if [ -f "${1}" ]
+then
+    case "${1}"
+    in
         *.7z)        bsdtar xf "${1}"                ;;
         *.Z)         uncompress "${1}"               ;;
         *.deb)       ar x "${1}"                     ;;
@@ -45,5 +92,5 @@ if [ -f "${1}" ]; then
         *)           echo "${1} cannot be extracted" ;;
     esac
 else
-    echo "${1} is not a valid file"
+    echo "ERROR: ${1} is not a valid file"
 fi
diff --git a/scripts/.local/share/bin/odus b/scripts/.local/share/bin/odus
--- a/scripts/.local/share/bin/odus
+++ b/scripts/.local/share/bin/odus
@@ -24,30 +24,34 @@ shell=0
 user="root"
 verbose=0
 
+prog_name="$(basename "${0}")"
+prog_desc="odus is kinda like sudo"
+prog_args="[COMMAND]"
+
 
 usage() {
     cat <<EOF
-Usage: odus [OPTIONS]... [COMMAND]
-odus - odus is kinda like sudo
+Usage: ${prog_name} [OPTION]... ${prog_args}
+${prog_name} - ${prog_desc}
 
 Options:
-    -h  show avalible options
-    -s  run a shell
-    -u  specify the user
-    -v  be verbose
+    -V, --version  show program version
+    -h, --help     show avalible options
+    -s, --shell    run a shell
+    -u, --user     specify the user
+    -v, --verbose  be verbose
+EOF
+}
 
-Copyright (c) 2021, Maciej Barć <xgqt@protonmail.com>
+version() {
+    cat <<EOF
+${prog_name} 9999
+
+Copyright (c) 2020-2021, Maciej Barć <xgqt@protonmail.com>
 Licensed under the GNU GPL v3 License
 EOF
 }
 
-
-if [ -z "${1}" ]
-then
-    echo "ERROR: Provide at lest one argument/option"
-    usage
-    exit 1
-fi
 
 while [ -n "${1}" ]
 do
@@ -57,10 +61,14 @@ do
             usage
             exit 0
             ;;
-        -s )
+        -V | -version | --version )
+            version
+            exit 0
+            ;;
+        -s | --shell )
             shell=1
             ;;
-        -u )
+        -u | --user )
             if [ -n "${2}" ]
             then
                 user="${2}"
@@ -71,8 +79,19 @@ do
                 exit 1
             fi
             ;;
-        -v )
+        -v | --verbose )
             verbose=1
+            ;;
+        "" )
+            echo "ERROR: Provide at lest one argument/option"
+            usage
+            exit 1
+            ;;
+        -* )
+            version
+            echo
+            usage
+            exit 1
             ;;
         * )
             command="${*}"
