add option to chroot to a directory

diff --git a/scripts/.local/share/bin/menu-chroot b/scripts/.local/share/bin/menu-chroot
--- a/scripts/.local/share/bin/menu-chroot
+++ b/scripts/.local/share/bin/menu-chroot
@@ -1,21 +1,143 @@
 #!/bin/sh
 
-cleanup () {
-    echo "Unmounting dev from $device_dir/dev..."; sleep 1
-    umount -l $device_dir/dev
-    echo "Unmounting proc from $device_dir/proc..."; sleep 1
-    umount -l $device_dir/proc
-    echo "Unmounting sys from $device_dir/sys..."; sleep 1
-    umount -l $device_dir/sys
-    echo "Unmounting tmp from $device_dir/tmp..."; sleep 1
-    umount -l $device_dir/tmp
-    echo "Unmounting $device from $device_dir..."; sleep 1
-    umount $device_dir || { echo "Unmount of $device_dir failed"; exit 1; }
-    echo "Removing $device_dir..."; sleep 1
-    rm -d $device_dir
+#  __  __                  
+# |  \/  | ___ _ __  _   _ 
+# | |\/| |/ _ \ '_ \| | | |
+# | |  | |  __/ | | | |_| |
+# |_|  |_|\___|_| |_|\__,_|
+#   ____ _                     _   
+#  / ___| |__  _ __ ___   ___ | |_ 
+# | |   | '_ \| '__/ _ \ / _ \| __|
+# | |___| | | | | | (_) | (_) | |_ 
+#  \____|_| |_|_|  \___/ \___/ \__|
+#
+# A simle chrooting script
+#
+# Chroot to a directory
+# or mount a device as
+# /mnt/mychroot-<device>
+# and chroot into it
+
+mount_dpst () {
+    #
+    # dev
+    echo "Mounting dev on $target_dir/dev..."; sleep 1
+    mount --rbind /dev $target_dir/dev
+    mount --make-rslave $target_dir/dev
+    #
+    # proc
+    echo "Mounting proc on $target_dir/proc..."; sleep 1
+    mount -t proc /proc $target_dir/proc
+    #
+    # sys
+    echo "Mounting sys $target_dir/sys..."; sleep 1
+    mount --rbind /sys $target_dir/sys
+    mount --make-rslave $target_dir/sys
+    #
+    # tmp
+    echo "Mounting tmp $target_dir/tmp..."; sleep 1
+    mount --rbind /tmp $target_dir/tmp
 }
 
-# Become root
+unmount_dpst () {
+    #
+    # dev
+    echo "Unmounting dev from $target_dir/dev..."; sleep 1
+    umount -l $target_dir/dev
+    #
+    # proc
+    echo "Unmounting proc from $target_dir/proc..."; sleep 1
+    umount -l $target_dir/proc
+    #
+    # sys
+    echo "Unmounting sys from $target_dir/sys..."; sleep 1
+    umount -l $target_dir/sys
+    #
+    # tmp
+    echo "Unmounting tmp from $target_dir/tmp..."; sleep 1
+    umount -l $target_dir/tmp
+}
+
+target_chroot () {
+    # chroot
+    echo "Chrooting to $target_dir..."; sleep 3
+    chroot $target_dir /bin/bash
+}
+
+cleanup () {
+    echo "Removing $target_dir..."; sleep 1
+    rm -d $target_dir
+}
+
+main () {
+
+    # Show devices and their mountpoints
+    lsblk
+
+    ### Chroot to device or directory
+    #
+    echo "Chroot to:"
+    echo "[1] Device"
+    echo "[2] Directory"
+    echo "[3] Exit"
+    read -r d_or_d
+
+    case $d_or_d in
+
+	1)
+	    ### Device option
+	    #
+	    echo "Select Device (type path)"
+	    #
+	    # Example: /dev/sdb1
+	    #
+	    read -r device
+	    target_dir=/mnt/mychroot-$(basename $device)
+
+	    mkdir $target_dir
+	    echo "Mounting device $device on $target_dir..."; sleep 1
+	    mount $device $target_dir || { echo "Mount failed"; cleanup; exit 1; }
+
+	    mount_dpst
+	    target_chroot || { echo "Chroot failed! Exiting!"; unmount_dpst; cleanup; exit 1; }
+
+	    echo "You exited the chroot"; sleep 1
+	    unmount_dpst
+	    echo "Unmounting $device from $target_dir..."; sleep 1
+	    umount -l $target_dir || { echo "Unmount of $target_dir failed"; exit 1; }
+	    cleanup
+	    ;;
+	2)
+	    ### Directory option
+	    #
+	    echo "Type directory path"
+	    read -r target_dir
+
+	    mount_dpst
+	    target_chroot || { echo "Chroot failed! Exiting!"; unmount_dpst;  exit 1; }
+
+	    echo "You exited the chroot"; sleep 1
+	    unmount_dpst
+	    ;;
+	3)
+	    ### Exit option
+	    #
+	    echo "Exiting"
+	    ;;
+	*)
+	    ### In a different case
+	    #
+	    # Re-run main
+	    echo "Unknown option. Choose 1 (device) or 2 (directory) or 3 (exit)"
+	    main
+	    ;;
+
+    esac
+
+}
+
+# Become root and
+# run this script
 if [ "$(whoami)" != root ]; then
     if [ -f ./menu-chroot ]; then
 	sudo ./menu-chroot
@@ -23,41 +145,5 @@ if [ "$(whoami)" != root ]; then
 	sudo "$(command -v menu-chroot)"
     fi
 else
-    # Show devices and ther mountpoints
-    lsblk
-
-    printf "\nSelect Disk (type device path)\n"
-    read -r device
-    device_dir=/mnt/mychroot-$(basename $device)
-    
-    mkdir $device_dir
-    echo "Mounting device $device on $device_dir..."; sleep 1
-    mount $device $device_dir || { echo "Mount failed"; cleanup; exit 1; }
-
-    ### sys mounts
-    #
-    # dev
-    echo "Mounting dev on $device_dir/dev..."; sleep 1
-    mount --rbind /dev $device_dir/dev
-    mount --make-rslave $device_dir/dev
-    #
-    # proc
-    echo "Mounting proc on $device_dir/proc..."; sleep 1
-    mount -t proc /proc $device_dir/proc
-    #
-    # sys
-    echo "Mounting sys $device_dir/sys..."; sleep 1
-    mount --rbind /sys $device_dir/sys
-    mount --make-rslave $device_dir/sys
-    #
-    # tmp
-    echo "Mounting tmp $device_dir/tmp..."; sleep 1
-    mount --rbind /tmp $device_dir/tmp
-
-    # chroot
-    echo "Chrooting to $device_dir..."; sleep 1
-    chroot $device_dir /bin/bash
-
-    echo "You exited the chroot"; sleep 1
-    cleanup
+    main
 fi
