scripts/odus: fix final command execution; reorder options that would not have been hit
Signed-off-by: Maciej Barć <xgqt@protonmail.com>

diff --git a/scripts/.local/share/bin/odus b/scripts/.local/share/bin/odus
--- a/scripts/.local/share/bin/odus
+++ b/scripts/.local/share/bin/odus
@@ -42,6 +42,13 @@ EOF
 }
 
 
+if [ -z "${1}" ]
+then
+    echo "ERROR: Provide at lest one argument/option"
+    usage
+    exit 1
+fi
+
 while [ -n "${1}" ]
 do
     case "${1}"
@@ -57,20 +64,15 @@ do
             if [ -n "${2}" ]
             then
                 user="${2}"
+                shift
             else
                 echo "ERROR: Specify the user"
                 usage
                 exit 1
             fi
-            shift
             ;;
         -v )
             verbose=1
-            ;;
-        "" )
-            echo "ERROR: Provide at lest one argument/option"
-            usage
-            exit 1
             ;;
         * )
             command="${*}"
@@ -99,6 +101,6 @@ else
         usage
         exit 1
     else
-        eval "su" "-c" '"' "${command}" '"'
+        eval "su" "${user}" "-c" \" "${command}" \"
     fi
 fi
